version: '2'

services:
  mysql:
    extends:
      file: ./mysql/docker-compose.yml
      service: mysql
    volumes:
      - mysqllog:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

  mariadb:
    extends:
      file: ./mariadb/docker-compose.yml
      service: mariadb
    volumes:
      - mariadblog:/var/log/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    extends:
      file: ./phpmyadmin/docker-compose.yml
      service: phpmyadmin
    depends_on:
      - mysql
      - mariadb

  elasticsearch:
    extends:
      file: ./elasticsearch/docker-compose.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - pglog:/mnt/data:rw
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ./kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

volumes:
  mysqldata:
  mysqllog:
  mariadbdata:
  mariadblog:
  esdata:

networks:
  esnet:
    driver: bridge
