version: '2'

services:
  mysql:
    extends:
      file: ./mysql/docker-compose.yml
      service: mysql
    volumes:
      #- mysqllog:/var/lib/mysql-files
      - mysqllog:/tmp
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/scripts:/scripts

  #mariadb:
  #  extends:
  #    file: ./mariadb/docker-compose.yml
  #    service: mariadb
  #  volumes:
  #    - mariadblog:/var/lib/mysql-files
  #    - ./mariadb/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    extends:
      file: ./phpmyadmin/docker-compose.yml
      service: phpmyadmin
    depends_on:
      - mysql
  #    - mariadb

  elasticsearch:
    extends:
      file: ./elasticsearch/docker-compose.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - mysqllog:/mnt/data:rw
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ./kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

  schemaspy:
    extends:
      file: ./schemaspy/docker-compose.yml
      service: schemaspy
    depends_on:
      - mysql

  schemaspy_nginx:
    extends:
      file: ./schemaspy/docker-compose.yml
      service: schemaspy_nginx
    depends_on:
      - mysql

volumes:
  mysqldata:
  mysqllog:
  mariadbdata:
  mariadblog:
  esdata:
  schemaspydata:

networks:
  esnet:
    driver: bridge
