debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

# Traefik status page
[web]
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "geneious.naturalis.nl"
watch = true
exposedbydefault = false

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
email = "rudi.broekhuizen@naturalis.nl"
storage = "acme.json"
OnHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "grafana.geneious.naturalis.nl"
[[acme.domains]]
  main = "sqlpad.geneious.naturalis.nl"
